# NOTE: update this with your service name
service: emy-notes-api

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-east-1
  #region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  environment:
   tableName: emy-notes
 #  SAMPLE_ENV_VAR: ${env:SAMPLE_ENV_VAR}
  
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:ap-east-1:*:*"


functions:
  create:
    handler: create.main
    events:
      - http:
          path: emy-notes
          method: post
          cors: true
          authorizer: aws_iam
  get:
    handler: get.main
    events:
      - http:
          path: emy-notes/{id}
          method: get
          cors: true
          authorizer: aws_iam
  list:
    handler: list.main
    events:
      - http:
          path: emy-notes
          method: get
          cors: true
          authorizer: aws_iam   
  update:
    handler: update.main
    events:
      - http:
          path: emy-notes/{id}
          method: put
          cors: true                   
          authorizer: aws_iam
  delete:
    handler: delete.main
    events:
      - http:
          path: emy-notes/{id}
          method: delete
          cors: true
          authorizer: aws_iam
resources:
  - ${file(resources/api-gateway-errors.yml)}
          